apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ms-chatrelay
spec:
  replicas: 1
  selector:
      matchLabels:
        app: ms-chatrelay
  template:
    metadata:
      labels:
        app: ms-chatrelay
    spec:
      containers:
        - image: rsobook/ms-chatrelay:2.0.3
          name: ms-chatrelay
          env:
            - name: PORT
              value: '80'
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://ms-etcd:2379
            - name: KUMULUZEE_CONFIG_ETCD_HOSTS
              value: http://ms-etcd:2379
          ports:
          - containerPort: 5432
            protocol: TCP